[package]
name = "bzippr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.10.1"
clap = { version = "4.5.48", features = ["derive"] }
thiserror = "2.0.16"

[dev-dependencies]
test-case = "3.3.1"

[lints.rust]
dead_code = "allow"
